#if !defined(AFX__CALENDAR_H__C4E99AF9_22BF_4F10_B208_D1A620F12059__INCLUDED_)
#define AFX__CALENDAR_H__C4E99AF9_22BF_4F10_B208_D1A620F12059__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_Calendar wrapper class

class C_Calendar : public COleDispatchDriver
{
public:
	C_Calendar() {}		// Calls COleDispatchDriver default constructor
	C_Calendar(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_Calendar(const C_Calendar& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetYear();
	void SetYear(LPCTSTR lpszNewValue);
	CString GetMonth();
	void SetMonth(LPCTSTR lpszNewValue);
	CString GetDay();
	void SetDay(LPCTSTR lpszNewValue);
	BOOL GetLocked();
	void SetLocked(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__CALENDAR_H__C4E99AF9_22BF_4F10_B208_D1A620F12059__INCLUDED_)
