#if !defined(AFX__CHART_H__69D49935_17CA_4971_B088_5ADC272DEB1E__INCLUDED_)
#define AFX__CHART_H__69D49935_17CA_4971_B088_5ADC272DEB1E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_Chart wrapper class

class C_Chart : public COleDispatchDriver
{
public:
	C_Chart() {}		// Calls COleDispatchDriver default constructor
	C_Chart(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_Chart(const C_Chart& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetAxesColor();
	void SetAxesColor(unsigned long newValue);
	long GetXAxisLabelAngle();
	void SetXAxisLabelAngle(long nNewValue);
	long GetChartType();
	void SetChartType(long nNewValue);
	BOOL GetDisplayAxes();
	void SetDisplayAxes(BOOL bNewValue);
	BOOL GetDisplayDataLabels();
	void SetDisplayDataLabels(BOOL bNewValue);
	BOOL GetDisplayGridLines();
	void SetDisplayGridLines(BOOL bNewValue);
	BOOL GetDisplayLegend();
	void SetDisplayLegend(BOOL bNewValue);
	long GetFirstCol();
	long GetFirstRow();
	unsigned long GetGridLinesColor();
	void SetGridLinesColor(unsigned long newValue);
	long GetLastCol();
	long GetLastRow();
	long GetLineWidth();
	void SetLineWidth(long nNewValue);
	long GetPlotBy();
	void SetPlotBy(long nNewValue);
	BOOL GetScaleFont();
	void SetScaleFont(BOOL bNewValue);
	unsigned long GetWallColor();
	void SetWallColor(unsigned long newValue);
	void SetDataSource(long FirstRow, long FirstCol, long LastRow, long LastCol);
	void SetSeriesColor(long Series, unsigned long Color);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__CHART_H__69D49935_17CA_4971_B088_5ADC272DEB1E__INCLUDED_)
