#if !defined(AFX__COMBOBOX_H__AA92323F_E755_4522_808A_CE72FD07C797__INCLUDED_)
#define AFX__COMBOBOX_H__AA92323F_E755_4522_808A_CE72FD07C797__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// C_ComboBox wrapper class

class C_ComboBox : public COleDispatchDriver
{
public:
	C_ComboBox() {}		// Calls COleDispatchDriver default constructor
	C_ComboBox(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_ComboBox(const C_ComboBox& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void AddItem(LPCTSTR Item);
	void RemoveItem(short ListIndex);
	void Clear();
	long FindItem(LPCTSTR Item, long Length, BOOL MatchCase);
	BOOL GetAutoComplete();
	void SetAutoComplete(BOOL bNewValue);
	COleFont GetFont();
	long GetItemData(short Index);
	void SetItemData(short Index, long nNewValue);
	long GetListCount();
	long GetListIndex();
	void SetListIndex(long nNewValue);
	CString GetListItem(short ListIndex);
	long GetListWidth();
	void SetListWidth(long nNewValue);
	long GetListRows();
	void SetListRows(long nNewValue);
	BOOL GetLocked();
	void SetLocked(BOOL bNewValue);
	short GetNewIndex();
	void DropDown();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__COMBOBOX_H__AA92323F_E755_4522_808A_CE72FD07C797__INCLUDED_)
