// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_hpagebreaks.h"

// Dispatch interfaces referenced by this interface
#include "_PageBreak.h"


/////////////////////////////////////////////////////////////////////////////
// C_HPageBreaks properties

/////////////////////////////////////////////////////////////////////////////
// C_HPageBreaks operations

void C_HPageBreaks::Add(long Row)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030002, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Row);
}

void C_HPageBreaks::Remove(long Index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030003, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Index);
}

void C_HPageBreaks::Clear()
{
	InvokeHelper(0x60030004, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long C_HPageBreaks::Count()
{
	long result;
	InvokeHelper(0x60030005, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

C_PageBreak C_HPageBreaks::Item(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030007, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return C_PageBreak(pDispatch);
}
