// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_images.h"

// Dispatch interfaces referenced by this interface
#include "_image.h"


/////////////////////////////////////////////////////////////////////////////
// C_Images properties

/////////////////////////////////////////////////////////////////////////////
// C_Images operations

void C_Images::Add(LPCTSTR FilePath, LPCTSTR Key)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x60030002, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FilePath, Key);
}

void C_Images::AddPicture(LPDISPATCH Picture, LPCTSTR Key)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_BSTR;
	InvokeHelper(0x60030003, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Picture, Key);
}

void C_Images::Remove(const VARIANT& Key)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x60030004, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Key);
}

long C_Images::Count()
{
	long result;
	InvokeHelper(0x60030005, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

C_Image C_Images::Item(const VARIANT& Key)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x60030006, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		&Key);
	return C_Image(pDispatch);
}
