#if !defined(AFX__PAGESETUP_H__B8D2F488_8303_42B0_B911_D89956CCE652__INCLUDED_)
#define AFX__PAGESETUP_H__B8D2F488_8303_42B0_B911_D89956CCE652__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// C_PageSetup wrapper class

class C_PageSetup : public COleDispatchDriver
{
public:
	C_PageSetup() {}		// Calls COleDispatchDriver default constructor
	C_PageSetup(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_PageSetup(const C_PageSetup& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	float GetLeftMargin();
	void SetLeftMargin(float newValue);
	float GetRightMargin();
	void SetRightMargin(float newValue);
	float GetTopMargin();
	void SetTopMargin(float newValue);
	float GetBottomMargin();
	void SetBottomMargin(float newValue);
	float GetHeaderMargin();
	void SetHeaderMargin(float newValue);
	float GetFooterMargin();
	void SetFooterMargin(float newValue);
	long GetPaperSize();
	void SetPaperSize(long nNewValue);
	float GetPaperWidth();
	void SetPaperWidth(float newValue);
	float GetPaperHeight();
	void SetPaperHeight(float newValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	BOOL GetPrintFixedRow();
	void SetPrintFixedRow(BOOL bNewValue);
	BOOL GetPrintFixedColumn();
	void SetPrintFixedColumn(BOOL bNewValue);
	BOOL GetPrintGridlines();
	void SetPrintGridlines(BOOL bNewValue);
	BOOL GetBlackAndWhite();
	void SetBlackAndWhite(BOOL bNewValue);
	BOOL GetCenterHorizontally();
	void SetCenterHorizontally(BOOL bNewValue);
	BOOL GetCenterVertically();
	void SetCenterVertically(BOOL bNewValue);
	CString GetHeader();
	void SetHeader(LPCTSTR lpszNewValue);
	CString GetFooter();
	void SetFooter(LPCTSTR lpszNewValue);
	long GetHeaderAlignment();
	void SetHeaderAlignment(long nNewValue);
	long GetFooterAlignment();
	void SetFooterAlignment(long nNewValue);
	COleFont GetHeaderFont();
	void SetRefHeaderFont(LPDISPATCH newValue);
	COleFont GetFooterFont();
	void SetRefFooterFont(LPDISPATCH newValue);
	long GetPrintTitleRows();
	void SetPrintTitleRows(long nNewValue);
	long GetPrintTitleColumns();
	void SetPrintTitleColumns(long nNewValue);
	long GetPrintBottomTitleRows();
	void SetPrintBottomTitleRows(long nNewValue);
	long GetPrintRows();
	void SetPrintRows(long nNewValue);
	long GetPrintColumns();
	void SetPrintColumns(long nNewValue);
	CString GetPrinterName();
	void SetPrinterName(LPCTSTR lpszNewValue);
	CString GetDocumentName();
	void SetDocumentName(LPCTSTR lpszNewValue);
	long GetThinBorderLineWidth();
	void SetThinBorderLineWidth(long nNewValue);
	long GetThickBorderLineWidth();
	void SetThickBorderLineWidth(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__PAGESETUP_H__B8D2F488_8303_42B0_B911_D89956CCE652__INCLUDED_)
