#if !defined(AFX__PAGEBREAK_H__020EA938_4D57_4652_BC62_1DFE75723E53__INCLUDED_)
#define AFX__PAGEBREAK_H__020EA938_4D57_4652_BC62_1DFE75723E53__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_PageBreak wrapper class

class C_PageBreak : public COleDispatchDriver
{
public:
	C_PageBreak() {}		// Calls COleDispatchDriver default constructor
	C_PageBreak(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_PageBreak(const C_PageBreak& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetLocation();
	void SetLocation(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__PAGEBREAK_H__020EA938_4D57_4652_BC62_1DFE75723E53__INCLUDED_)
