// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_papersize.h"


/////////////////////////////////////////////////////////////////////////////
// C_PaperSize properties

/////////////////////////////////////////////////////////////////////////////
// C_PaperSize operations

CString C_PaperSize::GetPaperName()
{
	CString result;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_PaperSize::SetPaperName(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

float C_PaperSize::GetWidth()
{
	float result;
	InvokeHelper(0x68030001, DISPATCH_PROPERTYGET, VT_R4, (void*)&result, NULL);
	return result;
}

void C_PaperSize::SetWidth(float newValue)
{
	static BYTE parms[] =
		VTS_R4;
	InvokeHelper(0x68030001, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

float C_PaperSize::GetHeight()
{
	float result;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_R4, (void*)&result, NULL);
	return result;
}

void C_PaperSize::SetHeight(float newValue)
{
	static BYTE parms[] =
		VTS_R4;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}
