// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_papersizes.h"

// Dispatch interfaces referenced by this interface
#include "_papersize.h"


/////////////////////////////////////////////////////////////////////////////
// C_PaperSizes properties

/////////////////////////////////////////////////////////////////////////////
// C_PaperSizes operations

long C_PaperSizes::Count()
{
	long result;
	InvokeHelper(0x60030004, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

C_PaperSize C_PaperSizes::Item(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030005, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return C_PaperSize(pDispatch);
}

void C_PaperSizes::Refresh()
{
	InvokeHelper(0x60030006, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
