#if !defined(AFX__RANGE_H__830767C8_FCAB_47B0_A0D2_8219578A0E87__INCLUDED_)
#define AFX__RANGE_H__830767C8_FCAB_47B0_A0D2_8219578A0E87__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_Range wrapper class

class C_Range : public COleDispatchDriver
{
public:
	C_Range() {}		// Calls COleDispatchDriver default constructor
	C_Range(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_Range(const C_Range& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetFirstRow();
	long GetLastRow();
	long GetFirstCol();
	long GetLastCol();
	void Selected();
	void SetBackColor(unsigned long newValue);
	void SetForeColor(unsigned long newValue);
	void SetAlignment(long nNewValue);
	void SetLocked(BOOL bNewValue);
	void SetMask(long nNewValue);
	void SetCellType(long nNewValue);
	void SetPrintable(BOOL bNewValue);
	void SetWrapText(BOOL bNewValue);
	void SetBorders(long Edge, long nNewValue);
	void SetMergeCells(BOOL bNewValue);
	void SetFontName(LPCTSTR lpszNewValue);
	void SetFontSize(float newValue);
	void SetFontBold(BOOL bNewValue);
	void SetFontItalic(BOOL bNewValue);
	void SetFontUnderline(BOOL bNewValue);
	void SetFontStrikethrough(BOOL bNewValue);
	void ClearAll();
	void ClearText();
	void ClearFormat();
	void Merge();
	void DeleteByRow();
	void DeleteByCol();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__RANGE_H__830767C8_FCAB_47B0_A0D2_8219578A0E87__INCLUDED_)
