#if !defined(AFX__REPORTTITLE_H__D89528BB_51DA_4B8D_B6D8_FDF5A909A7E5__INCLUDED_)
#define AFX__REPORTTITLE_H__D89528BB_51DA_4B8D_B6D8_FDF5A909A7E5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// C_ReportTitle wrapper class

class C_ReportTitle : public COleDispatchDriver
{
public:
	C_ReportTitle() {}		// Calls COleDispatchDriver default constructor
	C_ReportTitle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_ReportTitle(const C_ReportTitle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CString GetImageKey();
	void SetImageKey(LPCTSTR lpszNewValue);
	long GetAlign();
	void SetAlign(long nNewValue);
	COleFont GetFont();
	void SetRefFont(LPDISPATCH newValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	BOOL GetPrintOnAllPages();
	void SetPrintOnAllPages(BOOL bNewValue);
	short GetHeight();
	void SetHeight(short nNewValue);
	short GetTrueHeight();
	void SetTrueHeight(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__REPORTTITLE_H__D89528BB_51DA_4B8D_B6D8_FDF5A909A7E5__INCLUDED_)
