// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_vpagebreaks.h"

// Dispatch interfaces referenced by this interface
#include "_pagebreak.h"


/////////////////////////////////////////////////////////////////////////////
// C_VPageBreaks properties

/////////////////////////////////////////////////////////////////////////////
// C_VPageBreaks operations

void C_VPageBreaks::Add(long Col)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030002, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Col);
}

void C_VPageBreaks::Remove(long Index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030003, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Index);
}

void C_VPageBreaks::Clear()
{
	InvokeHelper(0x60030004, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long C_VPageBreaks::Count()
{
	long result;
	InvokeHelper(0x60030005, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

C_PageBreak C_VPageBreaks::Item(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030007, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return C_PageBreak(pDispatch);
}
