#if !defined(AFX_AX_CIE_XYZ_H__84099E1F_CA77_4025_A717_E182DCE890E6__INCLUDED_)
#define AFX_AX_CIE_XYZ_H__84099E1F_CA77_4025_A717_E182DCE890E6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAX_CIE_XYZ wrapper class

class CAX_CIE_XYZ : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAX_CIE_XYZ)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x593cf92c, 0xf3c3, 0x4ebb, { 0xb0, 0x94, 0xfa, 0xee, 0x9b, 0xb2, 0x7d, 0x46 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetCIEType();
	void SetCIEType(short);
	BOOL GetShowBBC();
	void SetShowBBC(BOOL);
	BOOL GetBShowXY();
	void SetBShowXY(BOOL);
	float GetX();
	void SetX(float);
	float GetY();
	void SetY(float);
	BOOL GetBShowXYValue();
	void SetBShowXYValue(BOOL);
	CString GetSzPath();
	void SetSzPath(LPCTSTR);
	CString GetPassword();
	void SetPassword(LPCTSTR);
	CString GetTitle();
	void SetTitle(LPCTSTR);

// Operations
public:
	void Draw();
	void CopyBMP();
	void Print();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AX_CIE_XYZ_H__84099E1F_CA77_4025_A717_E182DCE890E6__INCLUDED_)
