#if !defined(AFX_IPLOTANNOTATIONX_H__A59A8875_8043_4DC2_87C9_96FECD36488E__INCLUDED_)
#define AFX_IPLOTANNOTATIONX_H__A59A8875_8043_4DC2_87C9_96FECD36488E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CiPlotAnnotationX wrapper class

class CiPlotAnnotationX : public COleDispatchDriver
{
public:
	CiPlotAnnotationX() {}		// Calls COleDispatchDriver default constructor
	CiPlotAnnotationX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotAnnotationX(const CiPlotAnnotationX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetReference();
	void SetReference(long nNewValue);
	double GetX();
	void SetX(double newValue);
	double GetY();
	void SetY(double newValue);
	double GetX2();
	void SetX2(double newValue);
	double GetY2();
	void SetY2(double newValue);
	double GetWidth();
	void SetWidth(double newValue);
	double GetHeight();
	void SetHeight(double newValue);
	unsigned long GetPenColor();
	void SetPenColor(unsigned long newValue);
	long GetPenStyle();
	void SetPenStyle(long nNewValue);
	long GetPenWidth();
	void SetPenWidth(long nNewValue);
	unsigned long GetBrushColor();
	void SetBrushColor(unsigned long newValue);
	long GetBrushStyle();
	void SetBrushStyle(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	CString GetChannelName();
	void SetChannelName(LPCTSTR lpszNewValue);
	unsigned long GetFontColor();
	void SetFontColor(unsigned long newValue);
	long GetTextRotation();
	void SetTextRotation(long nNewValue);
	BOOL GetUserCanMove();
	void SetUserCanMove(BOOL bNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetEnable();
	void SetEnable(BOOL bNewValue);
	BOOL GetUserCanSize();
	void SetUserCanSize(BOOL bNewValue);
	long PositionXToPixels(double Value);
	long PositionYToPixels(double Value);
	double PixelsXToPosition(long Value);
	double PixelsYToPosition(long Value);
	long GetImageIndex();
	void SetImageIndex(long nNewValue);
	long GetImageListIndex();
	void SetImageListIndex(long nNewValue);
	long GetTextHorzAlignment();
	void SetTextHorzAlignment(long nNewValue);
	long GetTextVertAlignment();
	void SetTextVertAlignment(long nNewValue);
	double GetTextHorzMargin();
	void SetTextHorzMargin(double newValue);
	double GetTextVertMargin();
	void SetTextVertMargin(double newValue);
	long GetLayer();
	void SetLayer(long nNewValue);
	BOOL GetUserSelected();
	void SetUserSelected(BOOL bNewValue);
	BOOL GetClipToAxes();
	void SetClipToAxes(BOOL bNewValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	long GetOuterMargin();
	void SetOuterMargin(long nNewValue);
	BOOL HitTest(long X, long Y);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IPLOTANNOTATIONX_H__A59A8875_8043_4DC2_87C9_96FECD36488E__INCLUDED_)
