#if !defined(AFX_IPLOTDATACURSORX_H__4406E136_F13B_4E29_A977_61A15E0FD81E__INCLUDED_)
#define AFX_IPLOTDATACURSORX_H__4406E136_F13B_4E29_A977_61A15E0FD81E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CiPlotDataCursorX wrapper class

class CiPlotDataCursorX : public COleDispatchDriver
{
public:
	CiPlotDataCursorX() {}		// Calls COleDispatchDriver default constructor
	CiPlotDataCursorX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotDataCursorX(const CiPlotDataCursorX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetChannelName();
	void SetChannelName(LPCTSTR lpszNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	BOOL GetUseChannelColor();
	void SetUseChannelColor(BOOL bNewValue);
	BOOL GetHintShow();
	void SetHintShow(BOOL bNewValue);
	BOOL GetHintHideOnRelease();
	void SetHintHideOnRelease(BOOL bNewValue);
	long GetHintOrientationSide();
	void SetHintOrientationSide(long nNewValue);
	double GetHintPosition();
	void SetHintPosition(double newValue);
	BOOL GetMenuItemVisibleValueXY();
	void SetMenuItemVisibleValueXY(BOOL bNewValue);
	BOOL GetMenuItemVisibleValueX();
	void SetMenuItemVisibleValueX(BOOL bNewValue);
	BOOL GetMenuItemVisibleValueY();
	void SetMenuItemVisibleValueY(BOOL bNewValue);
	BOOL GetMenuItemVisibleDeltaX();
	void SetMenuItemVisibleDeltaX(BOOL bNewValue);
	BOOL GetMenuItemVisibleDeltaY();
	void SetMenuItemVisibleDeltaY(BOOL bNewValue);
	BOOL GetMenuItemVisibleInverseDeltaX();
	void SetMenuItemVisibleInverseDeltaX(BOOL bNewValue);
	CString GetMenuItemCaptionValueXY();
	void SetMenuItemCaptionValueXY(LPCTSTR lpszNewValue);
	CString GetMenuItemCaptionValueX();
	void SetMenuItemCaptionValueX(LPCTSTR lpszNewValue);
	CString GetMenuItemCaptionValueY();
	void SetMenuItemCaptionValueY(LPCTSTR lpszNewValue);
	CString GetMenuItemCaptionDeltaX();
	void SetMenuItemCaptionDeltaX(LPCTSTR lpszNewValue);
	CString GetMenuItemCaptionDeltaY();
	void SetMenuItemCaptionDeltaY(LPCTSTR lpszNewValue);
	CString GetMenuItemCaptionInverseDeltaX();
	void SetMenuItemCaptionInverseDeltaX(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	unsigned long GetFontColor();
	void SetFontColor(unsigned long newValue);
	double GetPointer1Position();
	void SetPointer1Position(double newValue);
	double GetPointer2Position();
	void SetPointer2Position(double newValue);
	double GetValueX();
	double GetValueY();
	long GetStatus();
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetPopupEnabled();
	void SetPopupEnabled(BOOL bNewValue);
	long GetLayer();
	void SetLayer(long nNewValue);
	BOOL GetChannelAllowAll();
	void SetChannelAllowAll(BOOL bNewValue);
	BOOL GetChannelShowAllInLegend();
	void SetChannelShowAllInLegend(BOOL bNewValue);
	BOOL GetUserSelected();
	void SetUserSelected(BOOL bNewValue);
	BOOL GetMenuUserCanChangeOptions();
	void SetMenuUserCanChangeOptions(BOOL bNewValue);
	long GetPointerPenWidth();
	void SetPointerPenWidth(long nNewValue);
	BOOL HitTest(long X, long Y);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IPLOTDATACURSORX_H__4406E136_F13B_4E29_A977_61A15E0FD81E__INCLUDED_)
