#if !defined(AFX_IPLOTTOOLBARX_H__0CDD46FF_0F74_45E0_9754_33A44CBEEA6D__INCLUDED_)
#define AFX_IPLOTTOOLBARX_H__0CDD46FF_0F74_45E0_9754_33A44CBEEA6D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CiPlotToolBarX wrapper class

class CiPlotToolBarX : public COleDispatchDriver
{
public:
	CiPlotToolBarX() {}		// Calls COleDispatchDriver default constructor
	CiPlotToolBarX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CiPlotToolBarX(const CiPlotToolBarX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	double GetStartPercent();
	void SetStartPercent(double newValue);
	double GetStopPercent();
	void SetStopPercent(double newValue);
	BOOL GetShowCopyButton();
	void SetShowCopyButton(BOOL bNewValue);
	BOOL GetShowSaveButton();
	void SetShowSaveButton(BOOL bNewValue);
	BOOL GetShowPrintButton();
	void SetShowPrintButton(BOOL bNewValue);
	BOOL GetShowEditButton();
	void SetShowEditButton(BOOL bNewValue);
	long GetZOrder();
	void SetZOrder(long nNewValue);
	BOOL GetHorizontal();
	void SetHorizontal(BOOL bNewValue);
	BOOL GetShowResumeButton();
	void SetShowResumeButton(BOOL bNewValue);
	BOOL GetShowPauseButton();
	void SetShowPauseButton(BOOL bNewValue);
	BOOL GetShowAxesModeButtons();
	void SetShowAxesModeButtons(BOOL bNewValue);
	BOOL GetShowZoomInOutButtons();
	void SetShowZoomInOutButtons(BOOL bNewValue);
	BOOL GetShowZoomBoxButton();
	void SetShowZoomBoxButton(BOOL bNewValue);
	BOOL GetShowCursorButton();
	void SetShowCursorButton(BOOL bNewValue);
	void TurnOffCursor();
	BOOL GetZoomBoxActive();
	BOOL GetCursorActive();
	void DoButtonClickResume();
	void DoButtonClickPause();
	void DoButtonClickScrollAxesMode();
	void DoButtonClickZoomAxesMode();
	void DoButtonClickZoomBox();
	void DoButtonClickZoomOut();
	void DoButtonClickZoomIn();
	void DoButtonClickCursor();
	void DoButtonClickEdit();
	void DoButtonClickCopy();
	void DoButtonClickSave();
	void DoButtonClickPrint();
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetPopupEnabled();
	void SetPopupEnabled(BOOL bNewValue);
	double GetZoomInOutFactor();
	void SetZoomInOutFactor(double newValue);
	long GetWidth();
	long GetHeight();
	BOOL GetShowSelectButton();
	void SetShowSelectButton(BOOL bNewValue);
	void DoButtonClickSelect();
	BOOL GetSelectActive();
	long GetLayer();
	void SetLayer(long nNewValue);
	BOOL GetFlatButtons();
	void SetFlatButtons(BOOL bNewValue);
	BOOL GetSmallButtons();
	void SetSmallButtons(BOOL bNewValue);
	BOOL GetFlatBorder();
	void SetFlatBorder(BOOL bNewValue);
	BOOL GetUserSelected();
	void SetUserSelected(BOOL bNewValue);
	BOOL GetShowPreviewButton();
	void SetShowPreviewButton(BOOL bNewValue);
	void DoButtonClickPreview();
	BOOL HitTest(long X, long Y);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IPLOTTOOLBARX_H__0CDD46FF_0F74_45E0_9754_33A44CBEEA6D__INCLUDED_)
