//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MultiLang.rc
//
#define IDC_BUTTON_CAL                  3
#define ID_SELE                         4
#define ID_SAVE_EXIT                    5
#define IDD_ABOUTBOX                    100
#define CG_IDD_MYLEDBAR                 102
#define IDD_PAGE1                       102
#define CG_ID_VIEW_MYLEDBAR             103
#define IDB_SPLASH                      104
#define IDS_TOO_MANY_ROWS               104
#define CG_IDD_MYTESTBAR                105
#define CG_ID_VIEW_MYTESTBAR            106
#define CG_IDD_MYNOTEBAR                107
#define CG_ID_VIEW_MYNOTEBAR            108
#define CG_IDD_MYTYPEBAR                109
#define CG_ID_VIEW_MYTYPEBAR            110
#define ID_WIN                          111
#define IDS_TYPE_SHEET_CAPTION          111
#define CG_ID_VIEW_MYTESTBAR1           113
#define CG_IDR_POPUP_MY_SPEC_VIEW       114
#define IDR_MAINFRAME                   128
#define IDR_MYSPECTYPE                  129
#define IDC_HAND                        130
#define IDB_MATRIXLARGE                 133
#define IDB_MATRIXSMALL                 134
#define IDB_MATRIXTINY                  135
#define IDB_SMALLICONS                  136
#define IDD_TEST_INFO                   136
#define IDD_SELE_PARA                   137
#define IDD_DEBUG1                      139
#define IDD_SPECTRUM_CAL                140
#define IDD_OPTION1                     142
#define IDD_SETUP1                      143
#define IDD_DIALOG_SET_LEVEL            145
#define IDB_CIE1931                     145
#define IDI_CIE                         146
#define IDB_CIE1976                     146
#define IDI_SDCM                        147
#define IDI_DATA                        148
#define IDI_SPEC                        150
#define IDD_WHITE                       151
#define IDD_WL_CHECK                    152
#define IDD_LED_TYPE_CAL                154
#define IDD_CAL_ATT                     156
#define IDD_USB_SCAN                    157
#define IDD_PHO_BRIGHT                  158
#define IDD_TEST_CURR_VS_L              161
#define IDD_PAGE_CURR_VS_L_1            162
#define IDI_CURR_VS_L_1                 163
#define IDI_CURR_VS_L_2                 164
#define IDI_SPECTRUM_CAL                165
#define IDD_PARA_SELE                   166
#define IDD_FAST_LEVEL                  167
#define IDD_OPTION2                     168
#define IDD_CAL_FE                      169
#define IDD_OPTION3                     170
#define IDD_SET_HAAS                    171
#define IDD_DIALOG_KTY                  174
#define IDD_SELE_MODE                   175
#define IDD_EX_TEST_BOX                 176
#define IDD_DIALOG_TR_SELE              178
#define IDI_SPECT_CAL                   179
#define IDD_DIALOG_PHO_EFF              179
#define IDI_SPECT_CAL_U                 180
#define IDD_SELE_CT                     182
#define IDI_FLUX_CAL                    182
#define IDD_DEBUG2                      183
#define IDD_DEBUG3                      184
#define IDI_CIE_UV                      184
#define IDD_USE_CORRECT_XY              185
#define IDD_NEW_FLUX_CAL                186
#define IDD_DIALOG_FLUX                 187
#define IDD_DEBUG4                      187
#define IDD_INPUT_POWER                 188
#define IDD_FLUX_CAL                    189
#define IDD_SELF_K_EDIT                 190
#define IDD_SELF_PH_K                   192
#define IDD_DIALOG_RE_CAL_GE            195
#define IDD_LED_CLASS_EDIT              200
#define IDD_LED_CLASS_SET_PARA          201
#define IDD_LED_CLASS_DATA_EDIT         202
#define IDD_WY_DIALOG                   212
#define IDD_SET_POWER                   213
#define IDD_PAGE2                       214
#define IDD_SETUP2                      215
#define IDD_PAGE3                       216
#define IDD_SETUP3                      217
#define IDD_NAME                        218
#define IDD_CAL_FLUX                    219
#define IDD_PAGE_CURR_VS_L_2            220
#define IDD_PAGE_CURR_VS_T2             221
#define IDD_PAGE_CURR_VS_T1             222
#define IDD_TEST_CURR_VS_T              223
#define IDD_USB_SCAN_TR                 224
#define IDD_USB_CAL_TR                  225
#define IDD_SPECTRUM_CAL_U              226
#define IDD_DEBUG6                      227
#define IDD_DEBUG5                      229
#define IDD_SETUP4                      230
#define IDD_PAGE4                       231
#define IDD_CHECK_BW                    233
#define IDD_PAGE5                       234
#define IDD_SETUP5                      235
#define IDD_USB_WD_SCAN                 236
#define IDD_USB_WD_CAL                  237
#define IDC_DATA_LCD                    1000
#define IDC_EDIT_SET_VOL                1000
#define IDC_DATA_LCD2                   1001
#define IDC_EDIT_INT_TIME               1001
#define IDC_EDIT_SET_CURR               1001
#define IDC_CHECK_AUTO                  1002
#define IDC_EDIT_AVG_N                  1003
#define IDC_OPEN                        1003
#define IDC_COMBO_STC_TYPE              1003
#define IDC_EV                          1004
#define IDC_COMBO_STC_COM               1004
#define IDC_STATIC_INT_TIME             1005
#define IDC_BUTTON_SET                  1005
#define IDC_STC_S1                      1005
#define IDC_STATIC_AVG_N                1006
#define IDC_STC_S2                      1006
#define IDC_EDIT_MODEL                  1006
#define IDC_NOTE                        1007
#define IDC_BUTTON_GET                  1007
#define IDC_CHECK_DEMO                  1007
#define IDC_COMBO_TYPE                  1008
#define IDC_COMBO_MAIN_COM              1008
#define IDC_COMBO_COM                   1009
#define IDC_EDIT_T                      1009
#define IDC_COMBO_LAMP                  1009
#define IDC_STATIC_COM                  1010
#define IDC_EDIT_H                      1010
#define IDC_COMBO_LAMP2                 1010
#define IDC_WL                          1011
#define IDC_RANGE                       1011
#define IDC_EDIT_FACTORY                1011
#define IDC_BUTTON_EXCEL                1011
#define IDC_STATIC_S2                   1012
#define IDC_SN                          1012
#define IDC_EDIT_TESTER                 1012
#define IDC_CHECK_IP                    1013
#define IDC_EDIT_DATE                   1013
#define IDC_CHECK_NOTE                  1014
#define IDC_EDIT_REMARK                 1014
#define IDC_CHECK_XY                    1015
#define IDC_CHECK_UV                    1016
#define IDC_BUTTON_ADD                  1017
#define IDC_CHECK_TC                    1017
#define IDC_BUTTON_DEL                  1018
#define IDC_CHECK_LD                    1018
#define IDC_BUTTON_TEST                 1018
#define IDC_BUTTON_MOD                  1019
#define IDC_CHECK_PUR                   1019
#define IDC_BUTTON_START                1019
#define IDC_CHECK_LP                    1020
#define IDC_BUTTON_STOP                 1020
#define IDC_BUTTON_ADD2                 1021
#define IDC_CHECK_HW                    1021
#define IDC_BUTTON_EXIT                 1021
#define ID_SELE_USB                     1021
#define IDC_BUTTON_DEL2                 1022
#define IDC_CHECK_RR                    1022
#define ID_SELE_RS                      1022
#define IDC_CHECK_RA                    1023
#define IDC_CHECK_PH                    1024
#define IDC_CHECK_LINE                  1024
#define IDC_RADIO1                      1024
#define IDC_EDIT_PF                     1024
#define IDC_EDIT_PIX                    1025
#define IDC_RADIO2                      1025
#define IDC_RADIO7                      1026
#define IDC_DATE                        1026
#define IDC_EDIT_WL                     1027
#define IDC_RADIO9                      1027
#define IDC_STATIC_IP                   1027
#define IDC_EDIT_AD                     1028
#define IDC_SPIN_1                      1029
#define IDC_SELE_K                      1029
#define IDC_CHECK_ZOOM                  1030
#define IDC_EDIT_X1                     1031
#define IDC_EDIT_X2                     1032
#define IDC_CIE                         1032
#define IDC_BUTTON_OK                   1033
#define IDC_RADIO_P1                    1033
#define IDC_STATIC_X12                  1034
#define IDC_RADIO_P2                    1034
#define IDC_BUTTON_OK2                  1035
#define IDC_BUTTON_GET_HF               1035
#define IDC_LIST_WL                     1036
#define IDC_COMBO_STA_WL                1037
#define IDC_LIST                        1038
#define IDC_BUTTON_CHECK                1039
#define IDC_C                           1039
#define IDC_W_SAVE                      1040
#define IDC_EDIT_COR                    1040
#define IDC_EDIT_NUMBER                 1043
#define IDC_BUTTON_PEAK                 1044
#define IDC_CHECK_VF                    1045
#define IDC_EDIT_STATE                  1045
#define IDC_CHECK_IF                    1046
#define IDC_EDIT_STANDARD               1046
#define IDC_BUTTON_CALC                 1047
#define IDC_CAL_SAVE                    1047
#define IDC_BUTTON_OPEN                 1048
#define IDC_CHECK_P                     1049
#define IDC_SPECT                       1049
#define IDC_BUTTON_SAVE_COR             1050
#define IDC_BUTTON_W_SN                 1051
#define IDC_EDIT_SN                     1052
#define IDC_BUTTON_R_SN                 1053
#define IDC_GO_SCAN                     1053
#define IDC_EDIT_C1                     1054
#define IDC_EDIT_C2                     1055
#define IDC_EDIT_C3                     1056
#define IDC_ONE_SCAN                    1056
#define IDC_EDIT_C4                     1057
#define IDC_BUTTON_W_COR                1058
#define IDC_BUTTON_R_COR                1059
#define IDC_BUTTON_S_ON                 1060
#define IDC_BUTTON_S_OFF                1061
#define IDC_EDIT_HAAS_SN                1062
#define IDC_EDIT_SOFT_VER               1063
#define IDC_EDIT_STA_CURR               1064
#define IDC_EDIT_EPROM                  1064
#define IDC_EDIT_STA_PH                 1065
#define IDC_EDIT_DRIVER                 1065
#define IDC_EDIT_STA_TC                 1066
#define IDC_BUTTON_ON                   1067
#define IDC_BUTTON_OFF                  1068
#define IDC_BUTTON_ON2                  1068
#define IDC_EDIT_STA_VOL                1069
#define IDC_IP                          1071
#define IDC_STATIC_STA_PH               1072
#define IDC_CHECK_HAVE_POWER            1073
#define IDC_EDIT_AVE_NUM                1073
#define IDC_COMBO_INTERVAL_WL           1074
#define IDC_COMBO_POW_TYPE              1074
#define IDC_NUMBER                      1074
#define IDC_COMBO_POW_COM               1075
#define IDC_GET_ZERO                    1075
#define IDC_STATIC_S3                   1076
#define IDC_MODE                        1076
#define IDC_CHECK_PRINT_LOGO            1077
#define IDC_BUTTON_WY                   1077
#define IDC_CAL_12                      1077
#define IDC_COMBO_POS                   1078
#define IDC_COMBO_SOU_COM               1078
#define IDC_STATIC_LOGO                 1079
#define IDC_CAL_23                      1079
#define IDC_CAL_34                      1081
#define IDC_CIE1931                     1082
#define IDC_SHOW_K1                     1082
#define IDC_SDCM                        1083
#define IDC_SHOW_AD11                   1083
#define IDC_SHOW_K2                     1084
#define IDC_SHOW_AD21                   1085
#define IDC_SHOW_K3                     1086
#define IDC_SHOW_AD2                    1086
#define IDC_SHOW_AD31                   1087
#define IDC_SHOW_AD3                    1087
#define IDC_STATIC_S1                   1088
#define IDC_CHECK_CUR                   1088
#define IDC_SPIN3                       1088
#define IDC_SHOW_AD12                   1088
#define IDC_DRAW                        1089
#define IDC_SHOW_AD22                   1089
#define IDC_DRAW2                       1090
#define IDC_BUTTON_LL                   1090
#define IDC_SHOW_AD32                   1090
#define IDC_SPIN1                       1091
#define IDC_BUTTON_L                    1091
#define IDC_SHOW_AD4                    1091
#define IDC_BUTTON_R                    1092
#define IDC_BUTTON_RR                   1093
#define IDC_T                           1094
#define IDC_BUTTON_TYPE                 1096
#define IDC_WL_RANGE                    1097
#define IDC_BUTTON_SAVE                 1098
#define IDC_BUTTON_SAVE2                1099
#define IDC_EDIT_AUTO_TIME2             1102
#define IDC_EDIT_DISTANCE               1103
#define IDC_EDIT_I_K                    1104
#define IDC_LIST2                       1106
#define IDC_EDIT_DATA2                  1107
#define IDC_AVG_ERR                     1110
#define IDC_EDIT_DATA1                  1111
#define IDC_BUTTON_RESET                1111
#define IDC_CHECK_PRINT_PAGE            1111
#define IDC_BUTTON1                     1112
#define IDC_RADIO_TYPE1                 1113
#define IDC_BUTTON3                     1113
#define IDC_RADIO_TYPE2                 1114
#define IDC_BUTTON5                     1114
#define IDC_EDIT_D                      1115
#define IDC_BUTTON_CORR                 1115
#define IDC_BUTTON6                     1115
#define IDC_RADIO3                      1116
#define IDC_RADIO_COLOR1                1116
#define IDC_RADIO4                      1117
#define IDC_RADIO_COLOR2                1117
#define IDC_RADIO5                      1118
#define IDC_RADIO_TEST_TYPE1            1118
#define IDC_RADIO6                      1119
#define IDC_RADIO_TEST_TYPE2            1119
#define IDC_RADIO_COLOR5                1120
#define IDC_RADIO_MODE                  1121
#define IDC_RADIO_COLOR6                1121
#define IDC_RADIO8                      1122
#define IDC_RADIO_COLOR7                1122
#define IDC_BUTTON_CLOSE                1122
#define IDC_EDIT_R1                     1123
#define IDC_MSFLEXGRID1                 1124
#define IDC_EDIT_R2                     1124
#define IDC_MSFLEXGRID2                 1125
#define IDC_EDIT_R_AD1                  1125
#define IDC_BUTTON_INPUT                1125
#define IDC_EDIT_R_AD2                  1126
#define IDC_EDIT_X                      1127
#define IDC_BUTTON2                     1127
#define IDC_EDIT_Y                      1128
#define IDC_BUTTON4                     1128
#define IDC_EDIT_R_K                    1129
#define IDC_EDIT_TMP                    1129
#define IDC_CHECK_PRINT_C               1129
#define IDC_COMBO_BIN                   1130
#define IDC_EDIT_R3                     1130
#define IDC_CHECK_WY                    1131
#define IDC_EDIT_R_AD3                  1131
#define IDC_STATIC_SETUP                1132
#define IDC_RADIO_COLOR8                1132
#define IDC_BUTTON_DARK                 1132
#define IDC_COMBO1                      1133
#define IDC_COMBO_LED                   1134
#define IDC_BUTTON_DELETE               1136
#define IDC_CHECK_TYPE                  1137
#define IDC_TIME_AUTO                   1137
#define IDC_RADIO_SHOW1                 1138
#define IDC_RADIO_SHOW2                 1139
#define IDC_W_OPEN                      1140
#define IDC_CHECK_ATT                   1140
#define IDC_RADIO_SHOW3                 1140
#define IDC_RADIO_SHOW4                 1141
#define IDC_RADIO_COLOR3                1143
#define IDC_EDIT_STA_FLUX               1144
#define IDC_RADIO_COLOR4                1144
#define IDC_RADIO_REPORT1               1145
#define IDC_STATIC_A1                   1145
#define IDC_RADIO_REPORT2               1146
#define IDC_RADIO_ATT1                  1146
#define IDC_RADIO_ATT2                  1147
#define IDC_CHECK_LEVEL                 1148
#define IDC_CHECK1_MANU                 1148
#define IDC_CHECK_WHITE                 1149
#define IDC_EDIT_PH                     1149
#define IDC_STATIC_SAD                  1150
#define IDC_BUTTON_ZERO_C               1151
#define IDC_CHECK1                      1152
#define IDC_EDIT1                       1153
#define IDC_EDIT_B2                     1154
#define IDC_EDIT_SET_DO_LIMIT_AD        1154
#define IDC_STATIC_HALF                 1155
#define IDC_EDIT_Y1                     1155
#define IDC_CHECK_FLUX_APP              1156
#define IDC_EDIT_Y2                     1156
#define IDC_CHECK_TRIG                  1158
#define IDC_STATIC_TRIG                 1159
#define IDC_COMBO_R_SN                  1160
#define IDC_STATIC_MOD                  1161
#define IDC_COMBO_BUAD                  1161
#define IDC_EDIT_MODE_K                 1162
#define IDC_EDIT2                       1163
#define IDC_EDIT_CURR2                  1163
#define IDC_STATIC_MOD2                 1163
#define IDC_EDIT_WL2                    1163
#define IDC_EDIT_PX                     1163
#define IDC_EDIT_TMP_CALC               1163
#define IDC_EDIT_REMARKS                1163
#define IDC_EDIT_CURR_TMP               1163
#define IDC_EDIT_MODE_K2                1164
#define IDC_STATIC_NOTE                 1165
#define IDC_STATIC_I_S1                 1167
#define IDC_STATIC_I_S2                 1168
#define IDC_STATIC_I_S3                 1169
#define IDC_EDIT_INTRVAL_CURR           1169
#define IDC_COMBO_NAME                  1170
#define IDC_EDIT_TIME                   1170
#define IDC_EDIT_AVG                    1171
#define IDC_EDIT_DELAY                  1172
#define IDC_DATA                        1173
#define IDC_EDIT_DELAY_FAIL             1173
#define IDC_EDIT_NAME                   1174
#define IDC_EDIT_N                      1177
#define IDC_EDIT_CURR1                  1177
#define IDC_BUTTON_CAL_FLUX             1177
#define IDC_BUTTON_EXPORT               1180
#define IDC_PROGRESS                    1181
#define IDC_BUTTON_TEST_INFO            1182
#define IDC_CHECK_ZW                    1183
#define IDC_BUTTON_SEND                 1184
#define IDC_EDIT_AVE_N                  1184
#define IDC_CHECK_SHOW                  1185
#define IDC_EDIT_VOL                    1186
#define IDC_STATIC_L_SELE               1186
#define IDC_COMBO_L_SELE                1187
#define IDC_EDIT_Z2                     1187
#define IDC_EDIT_I2                     1187
#define IDC_EDIT_VOL2                   1187
#define IDC_SPIN5                       1188
#define IDC_EDIT_CURR                   1188
#define IDC_EDIT_Z3                     1188
#define IDC_EDIT_I3                     1188
#define IDC_SPIN2                       1189
#define IDC_TEST_SELF_K                 1189
#define IDC_EDIT_Z4                     1189
#define IDC_EDIT_CURR3                  1189
#define IDC_BUTTON_TEST1                1190
#define IDC_STATIC_MOD_S2               1190
#define IDC_EDIT_U                      1191
#define IDC_BUTTON_TEST2                1191
#define IDC_EDIT_HALF                   1191
#define IDC_EDIT_I                      1192
#define IDC_EDIT_SDCM1                  1193
#define IDC_EDIT_P                      1193
#define IDC_CHECK_ALL                   1193
#define IDC_EDIT_SDCM2                  1194
#define IDC_EDIT_PRINT_TITLE            1194
#define IDC_EDIT_PRINT_COMPANY          1195
#define IDC_CHECK_INFO                  1196
#define IDC_EDIT_PLUSE_TIME             1196
#define IDC_EDIT_PRINT_ADDR             1196
#define IDC_STATIC_P_S                  1197
#define IDC_STATIC_USB                  1197
#define IDC_STATIC_P_S2                 1198
#define IDC_COMBO_MODE                  1198
#define IDC_EDIT_PLUSE_NUM              1199
#define IDC_COMBO_MAIN_TYPE             1200
#define IDC_COMBO_TR_DATA               1200
#define IDC_CHECK_ZERO                  1201
#define IDC_EDIT_WL1                    1202
#define IDC_CHECK_RO                    1203
#define IDC_EDIT_AD1                    1205
#define IDC_COMBO_LAMP_TYPE             1205
#define IDC_CHECK_USB_CAL_FE            1205
#define IDC_BUTTON_ZERO                 1206
#define IDC_BUTTON_SELE_TEXT            1206
#define IDC_COMBO_SOU                   1206
#define IDC_EDIT_ZERO                   1207
#define IDC_EDIT_K                      1207
#define IDC_BUTTON_SELE_BK              1207
#define IDC_EDIT_PER_TIME               1207
#define IDC_COMBO_SELE                  1208
#define IDC_STATIC_TEXT                 1208
#define IDC_BUTTON_LAMP_OFF             1208
#define IDC_STATIC_BK                   1209
#define IDC_PROGRESS1                   1210
#define IDC_STATIC_S                    1210
#define IDC_CHECK_CRO                   1211
#define IDC_BUTTON_TEST_J               1212
#define IDC_CHECK_TIME_TEST             1212
#define IDC_STATIC_SELE                 1213
#define IDC_BUTTON_MOD_SN               1213
#define IDC_RADIO_PRINT_G1              1214
#define IDC_RADIO_PRINT_G2              1215
#define IDC_CHECK_HALF_WL               1216
#define IDC_STATIC_SUI                  1217
#define IDC_CHECK_PHO_EFF               1219
#define IDC_EDIT_B1                     1220
#define IDC_BUTTON_PHO                  1221
#define IDC_EDIT_K1                     1222
#define IDC_STATIC_B                    1222
#define IDC_EDIT_K2                     1223
#define IDC_STATIC_Y                    1223
#define IDC_EDIT_K3                     1224
#define IDC_CIE1976                     1224
#define IDC_STATIC_LEVEL                1225
#define IDC_COMBO_RANGE                 1226
#define IDC_STATIC_HG_HF                1226
#define IDC_STATIC_BW                   1226
#define IDC_STATIC_MAIN                 1227
#define IDC_STATIC_WL_HF                1227
#define IDC_BUTTON_SAMP                 1229
#define IDC_EDIT_ZERO1                  1230
#define IDC_SET_STC                     1230
#define IDC_EDIT_ZERO2                  1231
#define IDC_EDIT_ZERO3                  1232
#define IDC_EDIT_ZERO4                  1233
#define IDC_COMBO_PE                    1234
#define IDC_EDIT_AD_CALC                1234
#define IDC_STATIC_PE                   1235
#define IDC_CHECK_NOT_USE_COLOR         1235
#define IDC_RADIO_T_TYPE1               1236
#define IDC_RADIO_T_TYPE2               1237
#define IDC_EDIT_FLUX                   1238
#define IDC_EDIT_PER                    1238
#define IDC_EDIT_FLUX_CHECK             1239
#define IDC_EDIT_PER2                   1239
#define IDC_EDIT_DW                     1240
#define IDC_EDIT_NUM                    1241
#define IDC_CHECK_PH_S_P                1241
#define IDC_CHECK_PRINT_PH_             1242
#define IDC_COMBO_LIST_CAL_SELE         1243
#define IDC_CHECK_USE_EX_TEST_BOX       1243
#define IDC_STATIC_LIST_S               1244
#define IDC_COMBO_TEST_SIG_TYPE         1244
#define IDC_EDIT_PATH_NAME              1245
#define IDC_CHECK_LIST_CAL              1245
#define IDC_COMBO_PASS_OUT_DEF          1245
#define IDC_RADIO_N_TYPE1               1246
#define IDC_COMBO_FAIL_OUT_DEF          1246
#define IDC_BUTTON_SELE                 1247
#define IDC_RADIO_N_TYPE2               1247
#define IDC_COMBO_PASS_OUT_DEF2         1247
#define IDC_BUTTON_SET_OK               1248
#define IDC_CHECK_PRINT_CHECKER         1248
#define IDC_COMBO_FAIL_OUT_DEF2         1248
#define IDC_EDIT_CHECKER                1249
#define IDC_COMBO_EX_TEST_BOX_COM       1249
#define IDC_EDIT_NEW_T                  1250
#define IDC_BUTTON_EDIT                 1251
#define IDC_EDIT_DELAY_PASS             1251
#define IDC_BUTTON_OK_SET               1252
#define IDC_EDIT_SET_DO_WL              1253
#define IDC_CHECK_DC                    1254
#define IDC_CHECK_R1_15                 1255
#define IDC_STATIC_S4                   1256
#define IDC_EDIT_TEST_FLUX              1256
#define IDC_STATIC_S5                   1257
#define IDC_BUTTON_SAVE_CAL             1257
#define IDC_STATIC_S6                   1258
#define IDC_BUTTON_START2               1258
#define IDC_BUTTON_STOP2                1259
#define IDC_CHECK_SAMPLE                1260
#define IDC_EDIT_PIX_SELE               1260
#define IDC_EDIT_INTTIME_2              1261
#define IDC_EDIT_INTTIME_1              1262
#define IDC_CHECK_USB_CAL_FLUX          1263
#define IDC_EDIT_INTTIME_INTERVAL       1263
#define IDC_PASS                        1264
#define IDC_CHECK_PRINT_E               1265
#define IDC_COLOR                       1265
#define IDC_EDIT_PH1                    1266
#define IDC_EDIT_MAX_SN_NUM             1266
#define IDC_EDIT_PH2                    1267
#define IDC_CHECK_USE_LED_TMP           1267
#define IDC_EDIT_PH_K                   1268
#define IDC_BUTTON_READ_TMP             1268
#define IDC_EDIT_SELF_PH_K              1269
#define IDC_EDIT_SET_TMP                1269
#define IDC_COMBO_WY_TYPE               1270
#define IDC_STATIC_T1                   1270
#define IDC_STATIC_T2                   1271
#define IDC_STATIC_T3                   1272
#define IDC_STATIC_T4                   1273
#define IDC_COMBO_LED_TMP_COM           1277
#define IDC_COMBO_SIG_TYPE              1278
#define IDC_CHECK_COLOR_CORRECT_STR     1281
#define IDC_EDIT_PIX_SELE2              1282
#define IDC_COMBO_STEP_TYPE             1283
#define IDC_COMBO_SR_2_ANGLE            1284
#define IDC_STATIC_SIG                  1285
#define IDC_CHECK_MOV                   1287
#define IDC_BUTTON_CAL_K                1292
#define IDC_EDIT_Z1                     1303
#define IDC_EDIT_I4                     1306
#define IDC_EDIT_I1                     1307
#define IDC_SHOW_AD1                    1308
#define IDC_BUTTON_READ_LAMP_FILE       1314
#define IDC_STATIC_IF                   1329
#define IDC_EDIT_D1                     1381
#define IDC_EDIT_D2                     1382
#define ID_EXPORT_CSV                   32771
#define ID_TEST                         32772
#define ID_TEST_CON                     32773
#define ID_DELETE                       32776
#define ID_VIEW_SETBAR                  32777
#define ID_VIEW_DATABAR                 32778
#define ID_VIEW_TYPEBAR                 32779
#define ID_EXPORT_SPEC_CAV              32781
#define ID_OPTION                       32782
#define ID_SELE_SDCM                    32783
#define ID_DEBUG                        32784
#define ID_SPECTRUM_CAL                 32785
#define ID_SETUP                        32787
#define ID_SET_WY                       32788
#define ID_TEST_INFO                    32790
#define ID_TEST_STOP                    32792
#define ID_SHOW_CUR                     32794
#define ID_WL_CHECK                     32796
#define ID_DARK                         32798
#define ID_BUTTON_DARK                  32799
#define ID_BUTTON_FLUX                  32800
#define ID_PARA                         32801
#define ID_ENGLISH                      32802
#define ID_CHINESE                      32803
#define ID_CAL_FLUX                     32804
#define ID_CAL_TYPE                     32805
#define ID_ALL_SELE                     32807
#define ID_BUTTON_TRIG                  32808
#define ID_CAL_ATT_K                    32809
#define ID_TEST_UP                      32812
#define ID_PHO_BRESS                    32813
#define ID_POWER                        32814
#define ID_DEBUG_SOFT                   32815
#define ID_EDIT_WHITE                   32816
#define ID_EDIT_LEVEL                   32817
#define ID_EXPORT_ACCESS                32818
#define ID_TEST_CURR_VS_L               32819
#define ID_SHOW_MODE_SELE               32820
#define ID_MODE_INTTIME                 32821
#define ID_TEST_STC                     32822
#define ID_TEST_CURR_VS_T               32823
#define ID_REMOVE_DARK                  32824
#define ID_USE_H_L_K                    32825
#define ID_EXPORT_JPG                   32827
#define ID_SCAN_TR_RR                   32832
#define ID_SPECT_CAL_U                  32833
#define ID_TPS_METERS                   32834
#define ID_VPS_METERS                   32835
#define ID_SELF_PH                      32836
#define ID_CAL_PL_FLUX                  32837
#define ID_EXPORT_OSRAM1                32838
#define ID_VPS_1010B                    32839
#define ID_CHECK_BW                     32840
#define ID_EXPORT_ALL_SPEC              32841
#define ID_GPIB_KEITHLEY_2420           32842
#define ID_RS232_REMOTE_COMM            32843
#define ID_CORRECT_XY                   32844
#define ID_USE_CORRECT_XY               32845
#define ID_EDIT_COPY_TXT_1              32846
#define ID_COLOR_CORRECT                32847
#define ID_COLOR_CORRECT_SELE           32848
#define ID_COLOR_CORRECT_EDIT           32849
#define ID_COLOR_CORRECT_EVERY_SET      32850
#define ID_WAIT_LAMP                    32851
#define ID_EX_TEST_BOX_SHOW             32852
#define ID_DPS_PC                       32853
#define ID_EXDTR                        32854
#define ID_WD_TEST                      32855
#define ID_MOD_GE                       32857
#define ID_EXPORT_PHS                   32858
#define INDICATOR_LOGO                  59142
#define ID_INDICATOR_MODE               59143
#define ID_INDICATOR_CAL                59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1286
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
