//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HighPowerInterface.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HIGHPOWERINTERFACE_DIALOG   102
#define IDR_MAINFRAME                   128
#define IDI_ICON0                       128
#define IDR_MENU1                       129
#define IDR_TOOLBAR1                    130
#define IDD_Controls                    132
#define IDD_ShowTest                    133
#define IDD_Statistic                   134
#define IDD_Bin                         135
#define IDD_Diagram                     136
#define IDD_ShootDiagram                136
#define IDD_AuthorityView               137
#define IDD_ChangePassword              138
#define IDD_Login                       139
#define IDD_SetParameter                140
#define IDD_SystemSetting               141
#define IDD_CIEDiagam                   142
#define IDD_SpectrumDiagram             143
#define IDD_CIEDiagram                  144
#define IDD_Spectrum                    146
#define IDD_Status                      147
#define IDD_ShowTestPopup               150
#define IDD_Setting                     151
#define IDD_AddUsersDlg                 153
#define IDD_DeleteUsersDlg              154
#define IDD_Level                       155
#define IDD_Register                    156
#define IDD_INITIAL                     157
#define IDD_Chip1Dlg                    158
#define IDD_Chip2Dlg                    159
#define IDD_Chip3Dlg                    160
#define IDD_SpectrumSetting             162
#define IDR_MENU2                       163
#define IDB_BITMAP1                     164
#define IDB_BITMAP2                     165
#define IDB_BITMAP4                     177
#define IDB_Login                       177
#define IDB_BITMAP3                     179
#define IDB_Add                         179
#define IDB_BITMAP5                     182
#define IDB_Delete                      182
#define IDI_ICON1                       184
#define IDI_ICON2                       185
#define IDI_ICON3                       186
#define IDI_ICON4                       188
#define IDB_BitmapNormal                189
#define IDB_BitmapMouseDown             190
#define IDB_BitmapHigh                  191
#define IDB_BitmapDisable               192
#define IDB_BitmapNormal2               193
#define IDB_BitmapMouseDown2            194
#define IDB_BitmapHigh2                 195
#define IDB_BitmapDisable2              196
#define IDB_BITMAP6                     197
#define IDB_BITMAP                      197
#define IDB_BK1                         200
#define IDB_BK2                         201
#define IDB_BK3                         202
#define IDB_BK                          202
#define IDB_ToolBarBK                   204
#define IDB_CIE                         206
#define IDB_VERTICLE_SCROLLBAR_TOP      207
#define IDB_VERTICLE_SCROLLBAR_UPARROW  208
#define IDB_VERTICLE_SCROLLBAR_SPAN     209
#define IDB_VERTICLE_SCROLLBAR_DOWNARROW 210
#define IDB_VERTICLE_SCROLLBAR_BOTTOM   211
#define IDB_VERTICLE_SCROLLBAR_THUMB    212
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 213
#define IDB_HORIZONTAL_SCROLLBAR_SPAN   214
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 215
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  216
#define IDB_COLUMNHEADER_SPAN           217
#define IDB_COLUMNHEADER_START0         218
#define IDB_COLUMNHEADER_END0           219
#define IDB_Set1                        220
#define IDB_Setparam                    221
#define IDB_Setlevel                    222
#define IDB_CHIP1                       223
#define IDB_CHIP2                       224
#define IDB_CHIP3                       225
#define IDB_CHIP11                      226
#define IDB_CHIP21                      227
#define IDB_CHIP31                      228
#define IDB_CHIP12                      229
#define IDB_CHIP22                      230
#define IDB_CHIP32                      231
#define IDB_SettingBK                   232
#define IDB_CHIP13                      234
#define IDB_CHIP23                      235
#define IDB_CHIP33                      236
#define IDD_SetChipFeet                 237
#define IDD_SetSpmReadParam             238
#define IDD_SetSpmSaveRefer             239
#define IDD_SetSpmSaveDark              240
#define IDB_Dark                        241
#define IDB_Refer                       242
#define IDR_ACCELERATOR1                243
#define IDR_ACCELERATOR                 248
#define IDB_shootCIE                    249
#define IDB_Setting                     250
#define IDB_SpectrumSetting             251
#define IDB_ChangePassword              252
#define IDB_Initial                     253
#define IDB_Shoot                       254
#define IDB_Register                    255
#define IDD_EngineerLogin               257
#define IDD_Light                       258
#define IDB_Light                       259
#define IDB_ChipType                    261
#define IDD_ChipType                    264
#define IDB_BigZ21                      278
#define IDB_SmallZ21                    279
#define IDB_SmallT21                    280
#define IDB_SmallT22                    281
#define IDB_SmallT42                    282
#define IDB_SmallT63                    283
#define IDB_SmallT430A                  284
#define IDB_SmallT430B                  285
#define IDB_SmallT431A                  286
#define IDB_SmallT431B                  287
#define IDB_SmallZ22                    288
#define IDB_SmallZ3200                  289
#define IDB_SmallZ3201                  290
#define IDB_SmallZ3210                  291
#define IDB_SmallZ3211                  292
#define IDB_SmallZ4300                  293
#define IDB_SmallZ4301                  294
#define IDB_SmallZ4310                  295
#define IDB_SmallZ4311                  296
#define IDB_TypeBK                      297
#define IDB_BigZ22                      298
#define IDB_BigZ3200                    299
#define IDB_BigZ3201                    300
#define IDB_BigZ3210                    301
#define IDB_BigZ3211                    302
#define IDB_BigZ4300                    303
#define IDB_BigZ4301                    304
#define IDB_BigZ4310                    305
#define IDB_BigZ4311                    306
#define IDB_BigT21                      307
#define IDB_BigT22                      308
#define IDB_BigT42                      309
#define IDB_BigT63                      310
#define IDB_BigT430A                    311
#define IDB_BigT430B                    312
#define IDB_BigT431A                    313
#define IDB_BigT431B                    314
#define IDD_SetSpmReadLmp               325
#define IDD_SetSpmCompen                326
#define IDD_AccumulateLevel             327
#define IDR_MENU3                       328
#define IDR_MENU4                       329
#define IDB_Accumulate                  330
#define IDB_ListBK                      339
#define IDB_ColHeader                   349
#define IDB_ColHeader2                  350
#define IDB_BK12                        376
#define IDB_ArrowDown                   377
#define IDB_Button_MinusDarkDown        402
#define IDB_Button_MinusDarkHigh        403
#define IDB_Button_MinusDarkDisable     404
#define IDB_Button_SingleNormal         405
#define IDB_Button_SingleDown           406
#define IDB_Button_SingleHigh           407
#define IDB_Button_SingleDisable        408
#define IDB_Button_ContinueNormal       409
#define IDB_Button_ContinueDown         410
#define IDB_Button_ContinueHigh         411
#define IDB_Button_ContinueDisable      412
#define IDB_Button_AutoNormal           413
#define IDB_Button_AutoDown             414
#define IDB_Button_AutoHigh             415
#define IDB_Button_AutoDisable          416
#define IDB_Button_StopNormal           417
#define IDB_Button_StopDown             418
#define IDB_Button_StopHigh             419
#define IDB_Button_StopDisable          420
#define IDB_BinNum                      424
#define IDB_MainBK                      432
#define IDB_Button_MinusDarkNormal      434
#define IDB_Button_ContinueNormal2      443
#define IDB_Button_ContinueDown2        444
#define IDB_Button_ContinueHigh2        445
#define IDB_Button_ContinueDisable2     446
#define IDB_Button_AutoNormal2          447
#define IDB_Button_AutoDown2            448
#define IDB_Button_AutoHigh2            449
#define IDB_Button_AutoDisable2         450
#define IDB_Button_StopNormal2          451
#define IDB_Button_StopDown2            452
#define IDB_Button_StopHigh2            453
#define IDB_Button_StopDisable2         454
#define IDB_BinNum2                     455
#define IDB_TabHeadSetChip              471
#define IDB_TabHeadSetParam             472
#define IDB_TabHeadSetLevel             473
#define IDB_SetChipBK                   477
#define IDB_TabHeadChip2                505
#define IDB_TabHeadChip3                506
#define IDB_TabHeadChip1                509
#define IDB_SetParamBK2                 515
#define IDB_RegistBK                    519
#define IDB_SetParamBK                  524
#define IDB_SetSystemBK                 531
#define IDB_SetSpectrumBK               535
#define IDB_LoginBK                     536
#define IDB_ChangePsdBK                 537
#define IDB_AddUserBK                   538
#define IDB_DelUserBK                   539
#define IDB_SetLevelBK                  542
#define IDB_AccumulateBK                552
#define IDB_Button_AuthorityNormal      555
#define IDB_Button_AuthorityDown        556
#define IDB_Button_AuthorityHigh        557
#define IDB_Button_ChangePsdNormal      575
#define IDB_Button_ChangePsdDown        576
#define IDB_Button_ChangePsdHigh        577
#define IDB_Button_ChangePsdDisable     578
#define IDB_Wizard                      579
#define IDB_Button_LoginNormal          580
#define IDB_Button_LoginDown            581
#define IDB_Button_LoginHigh            582
#define IDB_Button_LoginDisable         583
#define IDB_EngineerBK                  584
#define IDB_Button_CancelNormal         585
#define IDB_Button_CancelDown           586
#define IDB_Button_CancelHigh           587
#define IDB_Button_CancelDisable        588
#define IDB_Button_DelNormal            589
#define IDB_Button_DelDown              590
#define IDB_Button_DelHigh              591
#define IDB_Button_DelDisable           592
#define IDB_Button_AddNormal            593
#define IDB_Button_AddDown              594
#define IDB_Button_AddHigh              595
#define IDB_Button_AddDisable           596
#define IDB_Button_CancelNormal2        597
#define IDB_Button_CancelDown2          598
#define IDB_Button_CancelHigh2          599
#define IDB_Button_CancelDisable2       600
#define IDB_Button_SureNormal2          601
#define IDB_Button_SureDown2            602
#define IDB_Button_SureHigh2            603
#define IDB_Button_SureDisable2         604
#define IDB_Button_CancelNormal3        605
#define IDB_Button_CancelDown3          606
#define IDB_Button_CancelHigh3          607
#define IDB_Button_CancelDisable3       608
#define IDB_Button_SureNormal           609
#define IDB_Button_SureDown             610
#define IDB_Button_SureHigh             611
#define IDB_Button_SureDisable          612
#define IDB_Button_CancelNormal0        613
#define IDB_Button_CancelDown0          614
#define IDB_Button_CancelHigh0          615
#define IDB_Button_CancelDisable0       616
#define IDB_Button_ElecTestNormal       617
#define IDB_Button_ElecTestDown         618
#define IDB_Button_ElecTestHigh         619
#define IDB_Button_ElecTestDisable      620
#define IDB_Button_OOIConfigNormal      621
#define IDB_Button_OOIConfigDown        622
#define IDB_Button_OOIConfigHigh        623
#define IDB_Button_OOIConfigDisable     624
#define IDB_Button_SaveNormal           625
#define IDB_Button_SaveDown             626
#define IDB_Button_SaveHigh             627
#define IDB_Button_SaveDisable          628
#define IDB_Button_GetSpecParamNormal   629
#define IDB_Button_GetSpecParamfigDown  630
#define IDB_Button_GetSpecParamHigh     631
#define IDB_Button_GetSpecParamDisable  632
#define IDB_Button_SaveNormal2          633
#define IDB_Button_SaveDown2            634
#define IDB_Button_SaveHigh2            635
#define IDB_Button_SaveDisable2         636
#define IDB_Button_CancelNormal4        638
#define IDB_Button_CancelDown4          639
#define IDB_Button_CancelHigh4          640
#define IDB_Button_CancelDisable4       641
#define IDB_Button_AddItemNormal        642
#define IDB_Button_AddItemDown          643
#define IDB_Button_AddItemHigh          644
#define IDB_Button_AddItemDisable       645
#define IDB_Button_DelItemNormal        646
#define IDB_Button_DelItemDown          647
#define IDB_Button_DelItemHigh          648
#define IDB_Button_DelItemDisable       650
#define IDB_Button_SaveNormal3          651
#define IDB_Button_SureNormal3          653
#define IDB_Button_SureDown3            654
#define IDB_Button_SureHigh3            655
#define IDB_Button_SureDisable3         656
#define IDB_Button_CancelNormal5        657
#define IDB_Button_CancelDown5          658
#define IDB_Button_CancelHigh5          659
#define IDB_Button_CancelDisable5       660
#define IDB_Button_ExitNormal           661
#define IDB_Button_ExitDown             662
#define IDB_Button_ExitHigh             663
#define IDB_Button_ExitDisable          664
#define IDB_Button_GetGainNormal        665
#define IDB_Button_GetGainDown          666
#define IDB_Button_GetGainHigh          667
#define IDB_Button_GetGainDisable       668
#define IDB_Button_InteTimeNormal       669
#define IDB_Button_InteTimeDown         670
#define IDB_Button_InteTimeHigh         671
#define IDB_Button_InteTimeDisable      672
#define IDB_Button_AddDarkNormal        673
#define IDB_Button_AddDarkDown          674
#define IDB_Button_AddDarkHigh          675
#define IDB_Button_AddDarkDisable       676
#define IDB_Button_clearDarkNormal      678
#define IDB_Button_clearDarkDown        679
#define IDB_Button_clearDarkHigh        680
#define IDB_Button_clearDarkDisable     681
#define DB_Button_ClearCalDown          691
#define IDB_Button_CalTestNormal        695
#define IDB_Button_CalTestDown          696
#define IDB_Button_CalTestHigh          697
#define IDB_Button_CalTestDisable       698
#define IDB_Button_GetCalNormal         699
#define IDB_Button_GetCalDown           700
#define IDB_Button_GetCalHigh           701
#define IDB_Button_GetCalDisable        702
#define IDB_Button_ClearCalNormal       703
#define IDB_Button_ClearCalDown         704
#define IDB_Button_ClearCalHigh         705
#define IDB_Button_ClearCalDisable      707
#define IDB_Button_LevelFileNormal      708
#define IDB_Button_LevelFileDown        709
#define IDB_Button_LevelFileHigh        710
#define IDB_Button_LevelFileDisable     711
#define IDB_Button_HandleLevelNormal    712
#define IDB_Button_HandleLevelDown      713
#define IDB_Button_HandleLevelHigh      714
#define IDB_Button_HandleLevelDisable   715
#define IDB_Button_ApplyLevelNormal     720
#define IDB_Button_ApplyLevelDown       721
#define IDB_Button_ApplyLevelHigh       722
#define IDB_Button_ApplyLevelDisable    723
#define IDB_Button_AuthorityDisable     724
#define IDB_Button_SingleNormal2        725
#define IDB_Button_SingleDown2          726
#define IDB_Button_SingleHigh2          727
#define IDB_Button_SingleDisable2       728
#define IDB_Button_MinusDarkNormal2     729
#define IDB_Button_MinusDarkDown2       730
#define IDB_Button_MinusDarkHigh2       731
#define IDB_Button_MinusDarkDisable2    732
#define IDB_GetTypeNormal               733
#define IDB_GetTypeDown                 734
#define IDB_GetTypeHigh                 735
#define IDB_GetTypeDisable              736
#define IDB_GetWL1Normal                737
#define IDB_GetWL1Down                  738
#define IDB_GetWL1High                  739
#define IDB_GetWL1Disable               740
#define IDB_GetWL2High                  741
#define IDB_GetWL2Disable               742
#define IDB_GetWL2Normal                743
#define IDB_GetWL2Down                  744
#define IDB_ShootBK                     746
#define IDB_setColor                    747
#define IDB_ShootFileNormal             748
#define IDB_ShootFileDown               749
#define IDB_ShootFileHigh               750
#define IDB_ShootFileDisable            751
#define IDB_ShowPointNormal             753
#define IDB_ShowPointDown               754
#define IDB_ShowPointHigh               755
#define IDB_ShowPointDisable            756
#define IDB_ClearPicNormal              757
#define IDB_ClearPicDown                758
#define IDB_ClearPicHigh                759
#define IDB_ClearPicDisable             760
#define IDB_ClearDotNormal              761
#define IDB_ClearDotDown                762
#define IDB_ClearDotHigh                763
#define IDB_ClearDotDisable             764
#define IDB_ApplyBTNormal               769
#define IDB_ApplyBTDown                 770
#define IDB_ApplyBTHigh                 771
#define IDB_ApplyBTDisable              772
#define IDB_ShowLevelNormal             773
#define IDB_ShowLevelDown               774
#define IDB_ShowLevelHigh               775
#define IDB_ShowLevelDisable            776
#define IDB_AddLevelNormal              777
#define IDB_AddLevelDown                778
#define IDB_AddLevelHigh                779
#define IDB_AddLevelDisable             780
#define IDB_DelLevelNormal              781
#define IDB_DelLevelDown                782
#define IDB_DelLevelHigh                783
#define IDB_DelLevelDisable             784
#define IDB_BinNumNormal                785
#define IDB_BinNumDown                  786
#define IDB_BinNumHigh                  787
#define IDB_BinNumDisable               788
#define IDB_DotNormal                   793
#define IDB_DotDown                     794
#define IDB_DotHigh                     795
#define IDB_DotDisable                  796
#define IDB_SetAuthorityNormal          797
#define IDB_SetAuthorityDown            798
#define IDB_SetAuthorityHigh            799
#define IDB_SetAuthorityDisable         800
#define IDB_ShowAuthority               801
#define IDB_StaFilePath                 803
#define IDB_ToolBar                     805
#define IDB_MainBK2                     809
#define IDB_SettingBK2                  810
#define IDB_SpmReadParam                815
#define IDB_ReferSpec                   818
#define IDB_DarkSpec                    819
#define IDB_LampFile                    821
#define IDB_FinalCal                    823
#define IDB_InitialBK                   830
#define IDB_LeftTime                    831
#define IDB_InitText                    832
#define IDB_InitBTNormal                833
#define IDB_InitBTDown                  834
#define IDB_InitBTHigh                  835
#define IDB_InitCancelNormal            836
#define IDB_InitCancelDown              837
#define IDB_InitCancelHigh              838
#define IDB_RegisterBTNormal            839
#define IDB_RegisterBTDown              840
#define IDB_RegisterBTHigh              841
#define IDB_RegisterCancelNormal        842
#define IDB_RegisterCancelDown          844
#define IDB_RegisterCancelHigh          845
#define IDB_LightBK                     856
#define IDB_Button_LightNormal          857
#define IDB_Button_LightDown            858
#define IDB_Button_LightHigh            861
#define IDB_Button_LightDisable         862
#define IDB_Button_CloseLightNormal     863
#define IDB_Button_CloseLightDown       864
#define IDB_Button_CloseLightHigh       865
#define IDB_Button_CloseLightDisable    866
#define IDB_CIE2                        876
#define IDB_shootCIE2                   877
#define IDB_shootCIE4                   881
#define IDB_Temperature2                885
#define IDB_Temperature                 886
#define IDD_HandleLevel                 894
#define IDD_showLevel                   895
#define IDD_SetPrint                    897
#define IDD_SetPrintForm                898
#define IDC_Maximize                    1001
#define IDC_Popup                       1002
#define IDC_ShowTest_List               1004
#define IDC_Bin_List                    1005
#define IDC_Statistic_List              1006
#define IDC_authoritychange             1008
#define IDC_ShowAuthority               1010
#define IDC_BinTotalNumber              1011
#define IDC_Average                     1014
#define IDC_Exit                        1016
#define IDC_EDIT1                       1017
#define IDC_machineType                 1017
#define IDC_Pixels                      1017
#define IDC_Xbefcal                     1017
#define IDC_MaxPwr                      1017
#define IDC_Voltage                     1017
#define IDC_CharacCode                  1017
#define IDC_XRate                       1017
#define IDC_XEnd                        1017
#define IDC_Diameter                    1017
#define IDC_ItemNum                     1017
#define IDC_ShowPower                   1017
#define IDC_PosX1                       1017
#define IDC_BoxFullNum                  1017
#define IDC_EDIT2                       1018
#define IDC_Oldpd                       1018
#define level_x                         1018
#define IDC_RegCode1                    1018
#define IDC_WaitInteDelay               1018
#define IDC_FocusItem                   1018
#define IDC_Name1                       1018
#define IDC_CodeFromHardware            1018
#define IDC_BUTTON2                     1019
#define IDC_firstCoeff                  1019
#define IDC_FailBin                     1019
#define levelstartbin                   1019
#define IDC_EDIT7                       1019
#define IDC_BUTTON3                     1020
#define IDC_secondCoeff                 1020
#define IDC_MiddleWave1                 1020
#define IDC_XValue                      1020
#define IDC_PosY1                       1020
#define IDC_BUTTON1                     1021
#define IDC_thirdCoeff                  1021
#define IDC_MiddleWave2                 1021
#define IDC_YRate                       1021
#define IDC_YEnd                        1021
#define IDC_EDIT9                       1021
#define IDC_PosX2                       1021
#define IDC_EDIT3                       1022
#define IDC_newpd                       1022
#define IDC_AddDark1                    1022
#define IDC_Exportlevelfile             1022
#define IDC_MiddlePin                   1022
#define IDC_RegCode2                    1022
#define IDC_XStart                      1022
#define IDC_PosY2                       1022
#define IDC_tempcode                    1022
#define IDC_Login                       1023
#define IDC_YStart                      1023
#define IDC_EDIT10                      1023
#define IDC_PosX3                       1023
#define IDC_changepassword              1024
#define level_x2                        1024
#define IDC_EDIT11                      1024
#define IDC_PosY3                       1024
#define IDC_EDIT12                      1025
#define IDC_SURE                        1026
#define IDC_EDIT13                      1026
#define IDC_TAB1                        1027
#define IDC_SettingTab                  1027
#define IDC_EDIT14                      1027
#define IDC_Once                        1028
#define IDC_Single                      1028
#define IDC_EDIT15                      1028
#define IDC_Continuous                  1029
#define IDC_EDIT8                       1029
#define IDC_Name2                       1029
#define IDC_Stop                        1030
#define IDC_Auto                        1030
#define IDC_EDIT16                      1030
#define IDC_Name3                       1030
#define IDC_Retest                      1031
#define IDC_EDIT17                      1031
#define IDC_Name4                       1031
#define IDC_Autotest                    1032
#define IDC_Stoptest                    1032
#define IDC_EDIT18                      1032
#define IDC_Name5                       1032
#define IDC_Showtemperature             1033
#define IDC_EDIT19                      1033
#define IDC_Name6                       1033
#define IDC_EDIT20                      1034
#define IDC_Name7                       1034
#define IDC_Total                       1035
#define IDC_EDIT21                      1035
#define IDC_Name8                       1035
#define IDC_EDIT22                      1036
#define IDC_Name9                       1036
#define IDC_Passnum                     1037
#define IDC_EDIT23                      1037
#define IDC_Name10                      1037
#define IDC_Failnum                     1039
#define IDC_BUTTON4                     1040
#define IDC_PosX4                       1040
#define IDC_Passper                     1041
#define IDC_GetMiddleWave2              1041
#define IDC_XYlevelFile                 1041
#define IDC_PosY4                       1041
#define IDC_BUTTON5                     1042
#define IDC_PosX5                       1042
#define IDC_TestTime                    1043
#define IDC_PosY5                       1043
#define IDC_BUTTON7                     1044
#define IDC_PosX6                       1044
#define ID_ShowBinNum                   1045
#define IDC_POL                         1045
#define IDC_TestSpeed                   1045
#define IDC_PosY6                       1045
#define IDC_Status                      1046
#define IDC_PosX7                       1046
#define IDC_PosY7                       1047
#define IDC_PosX8                       1048
#define IDC_PosY8                       1049
#define IDC_PosX9                       1050
#define IDC_CHECK1                      1051
#define IDC_Test_IF                     1051
#define IDC_testType                    1051
#define IDC_testway                     1051
#define IDC_SelectCIEPicture            1051
#define IDC_AccumulateLevel             1051
#define IDC_white                       1051
#define IDC_ItemCheck1                  1051
#define IDC_CHECK2                      1052
#define IDC_Test_IR                     1052
#define IDC_ShowScale                   1052
#define IDC_SetOrderbyhand              1052
#define IDC_AccuFirst                   1052
#define IDC_ItemCheck2                  1052
#define IDC_CHECK3                      1053
#define IDC_Test_VF                     1053
#define IDC_LevelStyle                  1053
#define IDC_MixLight                    1053
#define IDC_ItemCheck3                  1053
#define IDC_CHECK4                      1054
#define IDC_Test_VR                     1054
#define IDC_LevelAdjust                 1054
#define IDC_DeadLed                     1054
#define IDC_ItemCheck10                 1054
#define IDC_CHECK5                      1055
#define IDC_Test_DVF                    1055
#define IDC_EnableResize                1055
#define IDC_ItemCheck4                  1055
#define IDC_CHECK6                      1056
#define IDC_Test_THY                    1056
#define IDC_Accumulate                  1056
#define IDC_ItemCheck5                  1056
#define IDC_CHECK7                      1057
#define IDC_Test_IV                     1057
#define IDC_parallelrectDrag            1057
#define IDC_VFaverage                   1057
#define IDC_ItemCheck6                  1057
#define IDC_CHECK8                      1058
#define IDC_Test_XYZ                    1058
#define IDC_ItemCheck8                  1058
#define IDC_CHECK9                      1059
#define IDC_Test_WL                     1059
#define IDC_FigureRange                 1059
#define IDC_ItemCheck7                  1059
#define IDC_CHECK10                     1060
#define IDC_Test_PWL                    1060
#define IDC_ItemCheck9                  1060
#define IDC_CHECK11                     1061
#define IDC_Test_DeltaWL                1061
#define IDC_DataCode1                   1061
#define IDC_CHECK12                     1062
#define IDC_Test_CRI                    1062
#define IDC_DataCode2                   1062
#define IDC_CHECK13                     1063
#define IDC_Test_CCT                    1063
#define IDC_DataCode3                   1063
#define IDC_CHECK14                     1064
#define IDC_Test_PUR                    1064
#define IDC_DataCode4                   1064
#define IDC_CHECK15                     1065
#define IDC_Test_IE                     1065
#define IDC_DataCode5                   1065
#define IDC_Test_LE                     1066
#define IDC_CHECK16                     1066
#define IDC_DataCode6                   1066
#define IDC_CHECK17                     1067
#define IDC_DataCode7                   1067
#define IDC_CHECK18                     1068
#define IDC_DataCode8                   1068
#define IDC_CHECK19                     1069
#define IDC_DataCode9                   1069
#define IDC_CHECK20                     1070
#define IDC_DataCode10                  1070
#define IDC_NameCode1                   1071
#define IDC_LIST2                       1072
#define IDC_XYList                      1072
#define IDC_printlist                   1072
#define IDC_NameCode2                   1072
#define IDC_feedingClowNum              1072
#define IDC_NameCode3                   1073
#define IDC_NameCode4                   1074
#define IDC_NameCode5                   1075
#define IDC_NameCode6                   1076
#define IDC_SaveSetting                 1077
#define IDC_NameCode7                   1077
#define IDC_Cancel                      1078
#define IDC_Authority                   1078
#define IDC_NameCode8                   1078
#define IDC_ShowCurrentFile             1079
#define IDC_NameCode9                   1079
#define IDC_MinusDark                   1080
#define IDC_NameCode10                  1080
#define IDC_EDIT4                       1081
#define IDC_Ensurepd                    1081
#define IDC_RegCode3                    1081
#define IDC_LevelNum                    1081
#define IDC_XYFilePath                  1081
#define IDC_PosY9                       1082
#define IDC_NewEngineer                 1083
#define IDC_PosX10                      1083
#define IDC_password                    1084
#define IDC_PosY10                      1084
#define IDC_EnsurePassword              1085
#define IDC_Engineer                    1086
#define IDC_Delete                      1087
#define IDC_EDIT5                       1090
#define IDC_RegCode4                    1090
#define IDC_outboxdetail                1090
#define IDC_iniAll                      1091
#define IDC_Register                    1092
#define IDC_TAB_Chip                    1094
#define IDC_SetChipList1                1099
#define IDC_SetChipList2                1100
#define IDC_SetChipList3                1101
#define IDC_cbChiptype                  1103
#define IDC_cbIVtype                    1104
#define IDC_cbWLSteptype                1105
#define IDC_EDIT6                       1106
#define IDC_iniTimeRate                 1106
#define IDC_cbLighttype                 1106
#define IDC_levellist                   1107
#define IDC_cbWLSteptypeset             1107
#define IDC_cbWLType                    1108
#define IDC_SystemSave                  1109
#define IDC_checkTimes                  1110
#define IDC_validTimes                  1111
#define IDC_sendBinDelay                1112
#define IDC_minTestTime                 1113
#define IDC_Intercept                   1114
#define IDC_DiameterOptic               1114
#define IDC_CheckHardware               1114
#define IDC_SpectrumSet                 1115
#define IDC_OOIConfig                   1115
#define IDC_VRoffset                    1116
#define IDC_VRoffset2                   1117
#define IDC_VRoffset3                   1118
#define IDC_Bin_Chip1                   1119
#define IDC_Bin_Chip2                   1120
#define IDC_Bin_Chip3                   1121
#define IDC_DrawPoint                   1122
#define IDC_ShootPicture                1124
#define IDC_inputpoint                  1125
#define IDC_ClearPicture                1126
#define IDC_SetColor                    1127
#define IDC_IntegrationTime1            1128
#define IDC_Apply                       1128
#define IDC_cbWLSteptype1               1129
#define IDC_ShowLevelPicture            1129
#define IDC_IntegrationTime2            1130
#define IDC_cbOpticGain1                1130
#define IDC_ClearDot                    1130
#define IDC_IntegrationTime3            1131
#define IDC_cbOpticGain2                1131
#define IDC_cbWLSteptype3               1132
#define IDC_cbWLSteptype2               1133
#define IDC_AutoSetInteTime1            1134
#define IDC_CalibrationTest1            1135
#define IDC_ClearDark1                  1136
#define IDC_AutoSetInteTime2            1137
#define IDC_shootset                    1137
#define IDC_AddDark2                    1138
#define IDC_AutoGetOpticGain1           1138
#define IDC_ClearDark2                  1139
#define IDC_CalibrationTest2            1140
#define IDC_AddDark3                    1141
#define IDC_shootset2                   1141
#define IDC_ClearDark3                  1142
#define IDC_AutoGetOpticGain2           1142
#define IDC_CalibrationTest3            1143
#define IDC_cbOpticGain3                1144
#define IDC_AutoSetInteTime3            1145
#define IDC_ScanTimes                   1146
#define IDC_Boxcar                      1147
#define IDC_Showlevelfile               1149
#define IDC_Inportlevelfile             1150
#define IDC_levelfile                   1150
#define IDC_Savelevelfile               1151
#define IDC_Handlelevel                 1151
#define IDC_SpectrumPicture             1156
#define level_y                         1156
#define IDC_CIEPicture                  1157
#define IDC_YValue                      1157
#define IDC_GetMiddleWave1              1163
#define IDC_shootchip1                  1170
#define IDC_shootset3                   1171
#define IDC_shootchip2                  1171
#define IDC_shootchip3                  1172
#define IDC_inputset                    1173
#define IDC_lineset                     1174
#define IDC_rectset                     1175
#define IDC_Save                        1176
#define IDC_parallelrectset             1177
#define IDC_point2                      1181
#define IDC_point4                      1182
#define IDC_Ybefcal                     1182
#define IDC_point3                      1183
#define IDC_Xaftcal                     1183
#define IDC_point1                      1184
#define IDC_Yaftcal                     1184
#define IDC_KLV                         1185
#define IDC_KLI                         1186
#define IDC_BUTTON6                     1187
#define IDC_KLDelay                     1187
#define IDC_unit                        1188
#define IDC_POLV                        1188
#define IDC_POLI                        1189
#define IDC_unit2                       1189
#define IDC_TREE1                       1190
#define IDC_POLDelay                    1190
#define IDC_getSpectraPara              1191
#define IDC_DLedBin                     1191
#define IDC_Picture                     1192
#define IDC_TimeScale                   1193
#define IDC_ScanFile                    1196
#define IDC_FilePath                    1197
#define IDC_SaveDark                    1198
#define IDC_SaveRefer                   1199
#define IDC_InteTime                    1200
#define IDC_BoxcarWidth                 1202
#define IDC_Recommended                 1203
#define IDC_levelchip1                  1204
#define IDC_levelchip2                  1205
#define IDC_levelchip3                  1206
#define IDC_levelIF                     1207
#define IDC_levelIR                     1208
#define IDC_levelVF                     1209
#define IDC_levelVR                     1210
#define IDC_levelDVF                    1211
#define IDC_levelTHY                    1212
#define IDC_levelIV                     1213
#define IDC_levelWL                     1214
#define IDC_levelPWL                    1215
#define IDC_levelDeltaWL                1216
#define IDC_levelPUR                    1217
#define IDC_levelCCT                    1218
#define IDC_levelCRI                    1219
#define IDC_Applylevels                 1221
#define IDC_levelsnum                   1222
#define IDC_startbin                    1223
#define IDC_Min                         1224
#define IDC_BaseData                    1224
#define IDC_Max                         1225
#define IDC_LevelWay                    1225
#define IDC_OpenLmpFile                 1226
#define IDC_SaveAsSpec                  1227
#define IDC_ShowSpectrum                1228
#define IDC_AutoSetTime                 1229
#define IDC_onechip                     1230
#define IDC_Selectchip                  1230
#define IDC_twochip                     1231
#define IDC_PROGRESS                    1231
#define IDC_threechip                   1232
#define IDC_ShowProgress                1233
#define IDC_SCROLLBAR1                  1235
#define IDC_SPIN1                       1236
#define IDC_RADIOList                   1238
#define IDC_SpecUSB                     1239
#define IDC_SpecPC                      1240
#define IDC_SelUSB2000                  1241
#define IDC_SelPC2000                   1242
#define IDC_ShowPointList               1243
#define IDC_SetRange                    1245
#define IDC_InsertLevel                 1246
#define IDC_CoverLevel                  1247
#define IDC_AddLevel                    1248
#define IDC_DeleteLevel                 1249
#define IDC_SetLevel                    1251
#define IDC_SelectLevel                 1252
#define IDC_CheckBinNum                 1253
#define IDC_Current                     1254
#define IDC_Chiptype                    1255
#define IDC_LightOn                     1256
#define IDC_Packageway                  1256
#define IDC_LightOff                    1257
#define IDC_SetwayIF                    1257
#define IDC_SetwayIV                    1258
#define IDC_SetwayWL                    1259
#define IDC_FigureChipstyle             1260
#define IDC_Polarity                    1263
#define IDC_WLType                      1264
#define IDC_type0                       1265
#define IDC_Commonfoot                  1265
#define IDC_type1                       1266
#define IDC_Enlarge                     1266
#define IDC_type2                       1267
#define IDC_Smaller                     1267
#define IDC_type3                       1268
#define IDC_LeftTime                    1268
#define IDC_type4                       1269
#define IDC_Regist                      1269
#define IDC_type5                       1270
#define IDC_type6                       1271
#define IDC_LmpList                     1271
#define IDC_type7                       1272
#define IDC_CompenList                  1272
#define IDC_type8                       1273
#define IDC_AreaWay0                    1273
#define IDC_type9                       1274
#define IDC_AreaWay1                    1274
#define IDC_type10                      1275
#define IDC_SaveAs                      1275
#define IDC_type11                      1276
#define IDC_type12                      1277
#define IDC_ClearCalibration            1277
#define IDC_type13                      1278
#define IDC_GetCalibration              1278
#define IDC_type14                      1279
#define IDC_AutoGetOpticGain3           1279
#define IDC_type15                      1280
#define IDC_AutoList                    1280
#define IDC_type16                      1281
#define IDC_AddItem                     1281
#define IDC_type17                      1282
#define IDC_DeleteItem                  1282
#define IDC_ShootCal                    1283
#define ID_ExportXYLevel                1284
#define IDC_AutoListTotal               1284
#define IDC_Gif                         1285
#define IDC_WhiteList                   1285
#define IDC_DLedStatic                  1288
#define IDC_CalItemList                 1289
#define IDC_Accuracy                    1290
#define IDC_fastLevel                   1293
#define IDC_delItem                     1296
#define IDC_Test_VZ                     1297
#define IDC_Test_LV                     1298
#define IDC_ShowItem                    1298
#define IDC_AutoList2                   1299
#define IDC_fastSTATIC                  1300
#define IDC_whiteXY                     1301
#define IDC_enterEngineer               1302
#define IDC_delway                      1303
#define IDC_offsetList                  1304
#define IDC_ItemCode                    1306
#define IDC_selectItem                  1307
#define IDC_printMode                   1308
#define IDC_clearSet                    1309
#define IDC_printForm                   1310
#define CMB_STYLE                       1311
#define IDC_printPreview                1312
#define IDC_PreviewForm                 1313
#define IDC_MSCOMM1                     1314
#define IDC_Data1                       1315
#define IDC_Data2                       1316
#define IDC_BinMapList                  1316
#define IDC_Data3                       1317
#define IDC_StartClear                  1317
#define IDC_Data4                       1318
#define IDC_StopClear                   1318
#define IDC_Data5                       1319
#define IDC_NumInBox                    1319
#define IDC_Data6                       1320
#define IDC_outboxnum                   1320
#define IDC_Data7                       1321
#define IDC_temptest                    1321
#define IDC_Data8                       1322
#define IDC_Data9                       1323
#define IDC_Data10                      1324
#define ID_OpenFile                     32772
#define ID_SaveFile                     32773
#define ID_SaveOtherFile                32774
#define ID_SaveAs                       32774
#define ID_Exit                         32775
#define ID_SetParameter                 32776
#define ID_SystemSetting                32777
#define ID_TestOnce                     32778
#define ID_TestSingle                   32778
#define ID_TestContinuous               32779
#define ID_StopTest                     32780
#define ID_RestartTest                  32781
#define ID_CheckLog                     32782
#define ID_ClearUp                      32783
#define ID_Manual                       32784
#define ID_About                        32785
#define ID_Guest                        32786
#define ID_Engineer                     32787
#define ID_RegistInformation            32788
#define ID_Tool_OpenFile                32789
#define ID_Tool_SaveFile                32790
#define ID_Shoot                        32791
#define ID_ColorTemperature             32792
#define ID_Spectrum                     32793
#define ID_IF                           32794
#define ID_C1_IF                        32794
#define ID_IR                           32795
#define ID_VF                           32796
#define ID_VR                           32797
#define ID_DVF                          32798
#define ID_THY                          32799
#define ID_IV                           32800
#define ID_XYZ                          32801
#define ID_CCT                          32802
#define ID_PUR                          32803
#define ID_CRI                          32804
#define ID_DWL                          32805
#define ID_PWL                          32806
#define ID_FWL                          32807
#define ID_G                            32808
#define ID_ElectricalAllSelected        32809
#define ID_ElectricalAllUnselected      32810
#define ID_OpticalAllSelected           32811
#define ID_OpticalAllUnselected         32812
#define ID_Connect                      32814
#define ID_Tool_SaveOtherFile           32815
#define ID_Tool_SaveAs                  32815
#define ID_NewFile                      32816
#define ID_BUTTON32817                  32817
#define ID_SettingParam                 32817
#define ID_AddUsers                     32819
#define ID_DeleteUsers                  32820
#define ID_SetSpectrum                  32821
#define ID_C1_IR                        32822
#define ID_C1_VF                        32823
#define ID_C1_VR                        32824
#define ID_C1_DVF                       32825
#define ID_C1_THY                       32826
#define ID_C1_IV                        32827
#define ID_C1_XYZ_X                     32828
#define ID_C1_XYZ                       32828
#define ID_C1_WL                        32829
#define ID_C1_PWL                       32830
#define ID_C1_DeltaWL                   32831
#define ID_C1_PUR                       32832
#define ID_C1_CCT                       32833
#define ID_C1_CRI                       32834
#define ID_C2_IF                        32835
#define ID_C2_IR                        32836
#define ID_C2_VF                        32837
#define ID_C2_VR                        32838
#define ID_C2_DVF                       32839
#define ID_C2_THY                       32840
#define ID_C2_IV                        32841
#define ID_C2_XYZ_X                     32842
#define ID_C2_XYZ                       32842
#define ID_C2_WL                        32843
#define ID_C2_PWL                       32844
#define ID_C2_DeltaWL                   32845
#define ID_C2_PUR                       32846
#define ID_C2_CRI                       32847
#define ID_C2_CCT                       32848
#define ID_C3_IF                        32849
#define ID_C3_IR                        32850
#define ID_C3_VF                        32851
#define ID_C3_VR                        32852
#define ID_C3_DVF                       32853
#define ID_C3_THY                       32854
#define ID_C3_IV                        32855
#define ID_C3_XYZ_X                     32856
#define ID_C3_XYZ                       32856
#define ID_C3_WL                        32857
#define ID_C3_PWL                       32858
#define ID_C3_DeltaWL                   32859
#define ID_C3_PUR                       32860
#define ID_C3_CCT                       32861
#define ID_C3_CRI                       32862
#define ID_C1_XYZ_Y                     32863
#define ID_C2_XYZ_Y                     32864
#define ID_C3_XYZ_Y                     32865
#define ID_SaveTestedData               32866
#define ID_SetSpm                       32871
#define ID_Inportlevelfile              32872
#define ID_Savelevelfile                32873
#define ID_Exportlevelfile              32874
#define ID_LightOn                      32875
#define ID_LightOff                     32876
#define ID_CheckShowSetting             32877
#define ID_RADIOOneLine                 32878
#define ID_RADIOList                    32879
#define ID_TestAuto                     32880
#define ID_Operator                     32881
#define ID_Resistance                   32882
#define ID_Regist                       32883
#define ID_AutoAccumulate               32884
#define ID_WL                           32885
#define ID_DeltaWL                      32886
#define ID_Cut                          32887
#define ID_Copy                         32888
#define ID_Paste                        32889
#define ID_Delete                       32890
#define ID_ShootSet                     32891
#define ID_ImportXYLevel                32892
#define ID_SaveXYLevel                  32893
#define ID_ShowCIELine                  32895
#define ID_SaveShootDot                 32896
#define ID_LoadShootDot                 32897
#define ID_NewCIERect                   32898
#define ID_ExportBinCode                32900
#define ID_ExportNewCIE                 32901
#define ID_DeleteItem                   32903
#define ID_showLevelSet                 32904
#define ID_ImportXYLevel2               32906
#define ID_SaveXYLevel2                 32907
#define ID_ExportXYLevel2               32908
#define ID_SetPrint                     32909
#define ID_ClearBinCode                 32910
#define ID_ClearBinBox                  32911
#define ID_StartClearBox                32912
#define ID_StopClearBox                 32913

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        900
#define _APS_NEXT_COMMAND_VALUE         32914
#define _APS_NEXT_CONTROL_VALUE         1322
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
